"""Zhipu AI (BigModel/GLM) model provider implementation."""

import logging
from typing import Optional

from .openai_compatible import OpenAICompatibleProvider
from .shared import (
    ModelCapabilities,
    ProviderType,
    RangeTemperatureConstraint,
)

logger = logging.getLogger(__name__)


class ZhipuModelProvider(OpenAICompatibleProvider):
    """Zhipu AI GLM API provider (open.bigmodel.cn)."""

    FRIENDLY_NAME = "Zhipu AI"

    # Model configurations using ModelCapabilities objects
    MODEL_CAPABILITIES = {
        "glm-5.1": ModelCapabilities(
            provider=ProviderType.ZHIPU,
            model_name="glm-5.1",
            friendly_name="Zhipu AI (GLM-5.1)",
            context_window=200_000,
            max_output_tokens=163_840,
            supports_extended_thinking=True,
            supports_system_prompts=True,
            supports_streaming=True,
            supports_function_calling=True,
            supports_json_mode=True,
            supports_images=False,
            max_image_size_mb=0.0,
            supports_temperature=True,
            temperature_constraint=RangeTemperatureConstraint(0.0, 2.0, 0.7),
            description="GLM-5.1 (200K context, 160K output) - Next-gen agentic flagship for long-horizon coding loops (Apr 2026)",
            aliases=["glm5.1", "zhipu-5.1", "glm-flagship"],
            intelligence_score=19,
        ),
        "glm-5": ModelCapabilities(
            provider=ProviderType.ZHIPU,
            model_name="glm-5",
            friendly_name="Zhipu AI (GLM-5)",
            context_window=200_000,
            max_output_tokens=128_000,
            supports_extended_thinking=True,
            supports_system_prompts=True,
            supports_streaming=True,
            supports_function_calling=True,
            supports_json_mode=True,
            supports_images=False,
            max_image_size_mb=0.0,
            supports_temperature=True,
            temperature_constraint=RangeTemperatureConstraint(0.0, 2.0, 0.7),
            description="GLM-5 (200K context, 128K output) - 744B MoE reasoning model for complex system engineering and agentic tasks",
            aliases=["glm5", "zhipu-5"],
            intelligence_score=18,
        ),
        "glm-5-turbo": ModelCapabilities(
            provider=ProviderType.ZHIPU,
            model_name="glm-5-turbo",
            friendly_name="Zhipu AI (GLM-5 Turbo)",
            context_window=200_000,
            max_output_tokens=128_000,
            supports_extended_thinking=True,
            supports_system_prompts=True,
            supports_streaming=True,
            supports_function_calling=True,
            supports_json_mode=True,
            supports_images=False,
            max_image_size_mb=0.0,
            supports_temperature=True,
            temperature_constraint=RangeTemperatureConstraint(0.0, 2.0, 0.7),
            description="GLM-5 Turbo (200K context) - Optimized for tool use, long-chain execution, and fast agentic workflows",
            aliases=["glm5-turbo", "zhipu-turbo"],
            intelligence_score=16,
        ),
        "glm-5v-turbo": ModelCapabilities(
            provider=ProviderType.ZHIPU,
            model_name="glm-5v-turbo",
            friendly_name="Zhipu AI (GLM-5V Turbo)",
            context_window=200_000,
            max_output_tokens=128_000,
            supports_extended_thinking=True,
            supports_system_prompts=True,
            supports_streaming=True,
            supports_function_calling=True,
            supports_json_mode=True,
            supports_images=True,
            max_image_size_mb=20.0,
            supports_temperature=True,
            temperature_constraint=RangeTemperatureConstraint(0.0, 2.0, 0.7),
            description="GLM-5V Turbo (200K context) - Native multimodal model with vision, video, and coding capabilities (Apr 2026)",
            aliases=["glm5v-turbo", "glm-vision-turbo", "zhipu-vision"],
            intelligence_score=17,
        ),
        "glm-5v": ModelCapabilities(
            provider=ProviderType.ZHIPU,
            model_name="glm-5v",
            friendly_name="Zhipu AI (GLM-5V)",
            context_window=128_000,
            max_output_tokens=64_000,
            supports_extended_thinking=True,
            supports_system_prompts=True,
            supports_streaming=True,
            supports_function_calling=True,
            supports_json_mode=True,
            supports_images=True,
            max_image_size_mb=20.0,
            supports_temperature=True,
            temperature_constraint=RangeTemperatureConstraint(0.0, 2.0, 0.7),
            description="GLM-5V (128K context) - Multimodal visual reasoning with grounding and video understanding",
            aliases=["glm5v", "glm-vision"],
            intelligence_score=16,
        ),
        "glm-4.7": ModelCapabilities(
            provider=ProviderType.ZHIPU,
            model_name="glm-4.7",
            friendly_name="Zhipu AI (GLM-4.7)",
            context_window=200_000,
            max_output_tokens=65_535,
            supports_extended_thinking=True,
            supports_system_prompts=True,
            supports_streaming=True,
            supports_function_calling=True,
            supports_json_mode=True,
            supports_images=False,
            max_image_size_mb=0.0,
            supports_temperature=True,
            temperature_constraint=RangeTemperatureConstraint(0.0, 2.0, 0.7),
            description="GLM-4.7 (200K context) - 400B param model with strong coding (84.9% LiveCodeBench) and reasoning",
            aliases=["glm47", "zhipu-4.7"],
            intelligence_score=17,
        ),
        "glm-4.7-flash": ModelCapabilities(
            provider=ProviderType.ZHIPU,
            model_name="glm-4.7-flash",
            friendly_name="Zhipu AI (GLM-4.7 Flash)",
            context_window=200_000,
            max_output_tokens=65_535,
            supports_extended_thinking=True,
            supports_system_prompts=True,
            supports_streaming=True,
            supports_function_calling=True,
            supports_json_mode=True,
            supports_images=False,
            max_image_size_mb=0.0,
            supports_temperature=True,
            temperature_constraint=RangeTemperatureConstraint(0.0, 2.0, 0.7),
            description="GLM-4.7 Flash (200K context) - Free-tier fast model with strong coding and reasoning",
            aliases=["glm47-flash", "zhipu-flash-4.7"],
            intelligence_score=14,
        ),
        "glm-4.6": ModelCapabilities(
            provider=ProviderType.ZHIPU,
            model_name="glm-4.6",
            friendly_name="Zhipu AI (GLM-4.6)",
            context_window=200_000,
            max_output_tokens=128_000,
            supports_extended_thinking=True,
            supports_system_prompts=True,
            supports_streaming=True,
            supports_function_calling=True,
            supports_json_mode=True,
            supports_images=False,
            max_image_size_mb=0.0,
            supports_temperature=True,
            temperature_constraint=RangeTemperatureConstraint(0.0, 2.0, 0.7),
            description="GLM-4.6 (200K context) - Prior flagship with strong coding/agents",
            aliases=["glm46", "zhipu-4.6"],
            intelligence_score=16,
        ),
        "glm-4.6v": ModelCapabilities(
            provider=ProviderType.ZHIPU,
            model_name="glm-4.6v",
            friendly_name="Zhipu AI (GLM-4.6V)",
            context_window=128_000,
            max_output_tokens=16_384,
            supports_extended_thinking=False,
            supports_system_prompts=True,
            supports_streaming=True,
            supports_function_calling=True,
            supports_json_mode=True,
            supports_images=True,
            max_image_size_mb=20.0,
            supports_temperature=True,
            temperature_constraint=RangeTemperatureConstraint(0.0, 2.0, 0.7),
            description="GLM-4.6V (128K context) - 106B/12B MoE vision model with multi-page docs and video",
            aliases=["glm46v", "zhipu-vision-4.6"],
            intelligence_score=14,
        ),
    }

    def __init__(self, api_key: str, **kwargs):
        """Initialize Zhipu AI provider with API key."""
        # Set Zhipu AI base URL
        kwargs.setdefault("base_url", "https://open.bigmodel.cn/api/paas/v4")
        super().__init__(api_key, **kwargs)

    def get_provider_type(self) -> ProviderType:
        """Get the provider type."""
        return ProviderType.ZHIPU
